### ISSUE TITLE
something wrong with the path argument

### ISSUE THREAD

**Issue by git-ram** [chinokenochkan/miptools#1]
No matter what path you pass to preprocess( ), it keeps complaining : " No such file or directory: './data/test.dcm'  "

**Comment by enochkan** [comment]
hi @git-ram , I apologize for not getting back to you earlier. I've pushed a bug fix in version 0.0.4. Please update the package and try again. Let me know if you are able to do so :)

**Comment by enochkan** [comment]
@git-ram please let me know if it is working as expected, so I can close this issue. Thanks!

**Comment by git-ram** [comment]
Hi, you can go ahead and close this. Thank you for following up

**Comment by enochkan** [comment]
@git-ram thanks a lot! Let me know if you want to see any new features/ find any other bugs. Thanks for your contribution.
